### ISSUE TITLE
Deployment to Maven Central

### ISSUE THREAD

**Issue by stolp** [albfernandez/jboss-seam#40]
Is there any chance that releases are published on maven central or any other repository?

I would greatly appreciate that, as it eases my update process.

Thanks for your efforts!

**Comment by albfernandez** [comment]
Hi

I've just released a new version to maven.

```xml

<dependency>
    <groupId>com.github.albfernandez.seam</groupId>
    <artifactId>jboss-seam</artifactId>
    <version>2.3.24.ayg</version>
</dependency>
<dependency>
    <groupId>com.github.albfernandez.seam</groupId>
    <artifactId>jboss-seam-ui</artifactId>
    <version>2.3.24.ayg</version>
</dependency>
```

**Comment by stolp** [comment]
Way cool, thanks! Will try this tomorrow.

**Comment by stolp** [comment]
I finally found the time to test this.

I am a bit surprised, that the jboss-seam core artifact has been distributed with `packaging>ejb</packaging>` shouldn't that be `packaging>jar</packaging>` instead?

Is this intended?

**Comment by albfernandez** [comment]
I'm not sure, I only changed from the old deployment to jboss servers to new deployment to maven servers (and the coordinate change)
Do you think I must change to `<packaging>jar</packaging>` for the next release?

**Comment by stolp** [comment]
Comparing [https://repository.jboss.org/nexus/content/groups/public-jboss/jboss/jboss-seam/](https://repository.jboss.org/nexus/content/groups/public-jboss/jboss/jboss-seam/) and[https://maven.repository.redhat.com/techpreview/all/org/jboss/seam/jboss-seam/](https://maven.repository.redhat.com/techpreview/all/org/jboss/seam/jboss-seam/) I am also unsure now.

**Comment by stolp** [comment]
In my project, I have been including the seam core module as a jar in the past. It is just a .war btw., no ejb involved here.

I need to do some further investigation why we were switching to using our own repository to hold these artifacts in jar packaging format in 2013. As far as I can remember this was due to some custom patches and using a default jar-type dependency just worked.

Currently, I cannot resolve jboss-seam from your distribution, even by switching to <type>ejb</type> in this project.

Maybe I am missing something obvious here.

By looking at previous releases, I learned that the ejb packaging seems to be introduced with release 2.1.0GA, a long time ago.

I let ypu know about further results here.

**Comment by albfernandez** [comment]
I can make a new relese only changing the packaging. I'm not sure, but I think most (or all) use  cases will work with `jar`

**Comment by stolp** [comment]
Let me first check on my side. Your release is in-line with the previous releases, so we should not consider this as broken.

**Comment by klaros-testmanagement** [comment]
Sorry for the late reply.

I think I now finally understand the problem. 

<type>ejb</type> is working as should be expected.

Yet I think that the deployment to maven central is missing the bom component, so the seam core module dependency is not working.

After I manually uploaded the bom pom to our nexus everything is working as expected.

Maybe you can add that to the next release as well?

**Comment by albfernandez** [comment]
Thanks.

 I'll try to include bom pom in the next upload.
