### ISSUE TITLE
Remove ioc module

### ISSUE THREAD

**Issue by albfernandez** [albfernandez/jboss-seam#58]

**Comment by stolp** [comment]
@albfernandez  Out of curiosity: Why are you removing this?

**Comment by stolp** [comment]
I just noticed that we are actually using this (SpringTransaction) - So I would strongly prefer to see this continued.

**Comment by albfernandez** [comment]
Hi, I'm not using it and it is based in old Spring 3.1. This Spring version is too old, I thought nobody was using this module.

I'll keep it.

**Comment by stolp** [comment]
Due to the impressing backwards compatibility of Spring at least the part I am using is still running perfectly with Spring 5.3. Maybe we can upgrade the dependencies accordingly?

Thanks for keeping this!
